services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    runtime: nvidia
    environment:
      - PUID=1000
      - PGID=993
      - TZ=America/Chicago
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
      - JELLYFIN_PublishedServerUrl=http://10.0.0.x
    volumes:
      - /docker/jellyfin/config:/config
      - /data:/data
    ports:
      - "8096:8096"
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - TZ=America/Chicago
    volumes:
      - /docker/jellyfin/jellyseerr:/app/config
    ports:
      - "5055:5055"
    restart: unless-stopped

  jellystat:
    image: cyfershepard/jellystat:latest
    container_name: jellystat
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_IP=jellystat-db
      - POSTGRES_PORT=5432
      - JWT_SECRET=${JWT_SECRET}
      - TZ=America/Chicago
    ports:
      - "3000:3000"
    depends_on:
      - jellystat-db
    restart: unless-stopped

  jellystat-db:
    image: postgres:15.2
    container_name: jellystat-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - jellystat-db-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  jellystat-db-data:
